version: "3.9"
services:
  server1:
    image: server
    build:
      context: .
      dockerfile: Dockerfile_server
  server2:
    image: server
  server3:
    image: server
  server4:
    image: server
  client:
    image: client
    build:
      context: .
      dockerfile: Dockerfile_client
    command: ya.ru server1:50051 server2:50051 server3:50051 server4:50051  # servers might not start yet
